/* Generated by Yosys 0.22 (git sha1 f109fa3d4c5, gcc 8.3.1 -fPIC -Os) */

module lp_tree_serializer(CLK, RESET, SERIAL_OUT, PAR_IN);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  input CLK;
  wire CLK;
  input [15:0] PAR_IN;
  wire [15:0] PAR_IN;
  input RESET;
  wire RESET;
  wire \S0.SERIAL_OUT ;
  wire \S0.clk_gen[1].clk_gen[0].clks.clk90_o ;
  wire \S0.clk_gen[1].clk_gen[0].clks.d[0] ;
  wire \S0.clk_gen[1].clk_gen[0].clks.d[1] ;
  wire \S0.clk_gen[2].clk_gen[0].clks.d[0] ;
  wire \S0.clk_gen[2].clk_gen[0].clks.d[1] ;
  wire \S0.clk_gen[2].clk_gen[1].clks.d[0] ;
  wire \S0.clk_gen[2].clk_gen[1].clks.d[1] ;
  wire \S0.stage_gen[1].mux_gen[0].S.PAR_IN1 ;
  wire \S0.stage_gen[1].mux_gen[0].S.PAR_IN2 ;
  wire \S0.stage_gen[1].mux_gen[1].S.PAR_IN1 ;
  wire \S0.stage_gen[1].mux_gen[1].S.PAR_IN2 ;
  wire \S0.stage_gen[1].mux_gen[2].S.PAR_IN1 ;
  wire \S0.stage_gen[1].mux_gen[3].S.PAR_IN1 ;
  wire \S1.CLK ;
  wire \S1.SERIAL_OUT ;
  wire \S1.clk_gen[1].clk_gen[0].clks.clk90_o ;
  wire \S1.clk_gen[1].clk_gen[0].clks.d[0] ;
  wire \S1.clk_gen[1].clk_gen[0].clks.d[1] ;
  wire \S1.clk_gen[2].clk_gen[0].clks.d[0] ;
  wire \S1.clk_gen[2].clk_gen[0].clks.d[1] ;
  wire \S1.clk_gen[2].clk_gen[1].clks.d[0] ;
  wire \S1.clk_gen[2].clk_gen[1].clks.d[1] ;
  wire \S1.stage_gen[1].mux_gen[0].S.PAR_IN1 ;
  wire \S1.stage_gen[1].mux_gen[0].S.PAR_IN2 ;
  wire \S1.stage_gen[1].mux_gen[1].S.PAR_IN1 ;
  wire \S1.stage_gen[1].mux_gen[2].S.PAR_IN1 ;
  wire \S1.stage_gen[1].mux_gen[3].S.PAR_IN1 ;
  output SERIAL_OUT;
  wire SERIAL_OUT;
  wire \clkdiv0.d[0] ;
  wire \clkdiv0.d[1] ;
  wire \last_stage.PAR_IN1 ;
  wire \last_stage.PAR_IN2 ;
  wire \last_stage_inputs[0] ;
  wire \last_stage_inputs[1] ;
  sky130_fd_sc_hd__inv_4 _074_ (
    .A(\S1.clk_gen[1].clk_gen[0].clks.d[1] ),
    .Y(_063_)
  );
  sky130_fd_sc_hd__bufinv_8 _075_ (
    .A(\clkdiv0.d[0] ),
    .Y(\S1.CLK )
  );
  sky130_fd_sc_hd__buf_1 _076_ (
    .A(\clkdiv0.d[0] ),
    .X(_031_)
  );
  sky130_fd_sc_hd__buf_2 _077_ (
    .A(_031_),
    .X(_066_)
  );
  sky130_fd_sc_hd__inv_4 _078_ (
    .A(\S1.clk_gen[1].clk_gen[0].clks.d[0] ),
    .Y(\S1.clk_gen[1].clk_gen[0].clks.clk90_o )
  );
  sky130_fd_sc_hd__buf_1 _079_ (
    .A(\S1.clk_gen[1].clk_gen[0].clks.d[0] ),
    .X(_032_)
  );
  sky130_fd_sc_hd__buf_2 _080_ (
    .A(_032_),
    .X(_062_)
  );
  sky130_fd_sc_hd__inv_2 _081_ (
    .A(\S1.clk_gen[1].clk_gen[0].clks.d[0] ),
    .Y(_061_)
  );
  sky130_fd_sc_hd__inv_2 _082_ (
    .A(\clkdiv0.d[0] ),
    .Y(_065_)
  );
  sky130_fd_sc_hd__buf_1 _083_ (
    .A(\S0.clk_gen[1].clk_gen[0].clks.d[1] ),
    .X(_033_)
  );
  sky130_fd_sc_hd__buf_2 _084_ (
    .A(_033_),
    .X(_058_)
  );
  sky130_fd_sc_hd__inv_4 _085_ (
    .A(\S0.clk_gen[1].clk_gen[0].clks.d[1] ),
    .Y(_057_)
  );
  sky130_fd_sc_hd__buf_1 _086_ (
    .A(\clkdiv0.d[1] ),
    .X(_034_)
  );
  sky130_fd_sc_hd__buf_2 _087_ (
    .A(_034_),
    .X(_060_)
  );
  sky130_fd_sc_hd__inv_4 _088_ (
    .A(\S0.clk_gen[1].clk_gen[0].clks.d[0] ),
    .Y(\S0.clk_gen[1].clk_gen[0].clks.clk90_o )
  );
  sky130_fd_sc_hd__buf_1 _089_ (
    .A(\S0.clk_gen[1].clk_gen[0].clks.d[0] ),
    .X(_035_)
  );
  sky130_fd_sc_hd__buf_2 _090_ (
    .A(_035_),
    .X(_056_)
  );
  sky130_fd_sc_hd__inv_2 _091_ (
    .A(\S0.clk_gen[1].clk_gen[0].clks.d[0] ),
    .Y(_055_)
  );
  sky130_fd_sc_hd__bufinv_8 _092_ (
    .A(\clkdiv0.d[1] ),
    .Y(_059_)
  );
  sky130_fd_sc_hd__buf_1 _093_ (
    .A(CLK),
    .X(_036_)
  );
  sky130_fd_sc_hd__buf_2 _094_ (
    .A(_036_),
    .X(_054_)
  );
  sky130_fd_sc_hd__inv_2 _095_ (
    .A(CLK),
    .Y(_053_)
  );
  sky130_fd_sc_hd__inv_6 _096_ (
    .A(\S0.clk_gen[2].clk_gen[1].clks.d[0] ),
    .Y(_001_)
  );
  sky130_fd_sc_hd__inv_6 _097_ (
    .A(\S0.clk_gen[2].clk_gen[0].clks.d[0] ),
    .Y(_000_)
  );
  sky130_fd_sc_hd__inv_4 _098_ (
    .A(\S1.clk_gen[2].clk_gen[1].clks.d[0] ),
    .Y(_003_)
  );
  sky130_fd_sc_hd__inv_6 _099_ (
    .A(\S1.clk_gen[2].clk_gen[0].clks.d[0] ),
    .Y(_002_)
  );
  sky130_fd_sc_hd__inv_2 _100_ (
    .A(\S0.stage_gen[1].mux_gen[1].S.PAR_IN1 ),
    .Y(_037_)
  );
  sky130_fd_sc_hd__nand2_4 _101_ (
    .A(_000_),
    .B(_037_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__inv_2 _102_ (
    .A(\S0.stage_gen[1].mux_gen[1].S.PAR_IN2 ),
    .Y(_039_)
  );
  sky130_fd_sc_hd__nand2_2 _103_ (
    .A(_039_),
    .B(\S0.clk_gen[2].clk_gen[0].clks.d[0] ),
    .Y(_040_)
  );
  sky130_fd_sc_hd__nand3_2 _104_ (
    .A(_038_),
    .B(_040_),
    .C(\S0.clk_gen[1].clk_gen[0].clks.d[1] ),
    .Y(_041_)
  );
  sky130_fd_sc_hd__inv_2 _105_ (
    .A(\S0.stage_gen[1].mux_gen[0].S.PAR_IN1 ),
    .Y(_042_)
  );
  sky130_fd_sc_hd__inv_2 _106_ (
    .A(\S0.clk_gen[2].clk_gen[0].clks.d[1] ),
    .Y(_043_)
  );
  sky130_fd_sc_hd__nand2_2 _107_ (
    .A(_042_),
    .B(_043_),
    .Y(_044_)
  );
  sky130_fd_sc_hd__inv_2 _108_ (
    .A(\S0.stage_gen[1].mux_gen[0].S.PAR_IN2 ),
    .Y(_045_)
  );
  sky130_fd_sc_hd__nand2_2 _109_ (
    .A(_045_),
    .B(\S0.clk_gen[2].clk_gen[0].clks.d[1] ),
    .Y(_046_)
  );
  sky130_fd_sc_hd__nand3_2 _110_ (
    .A(_044_),
    .B(_046_),
    .C(_057_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__nand2_2 _111_ (
    .A(_041_),
    .B(_047_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__nand2_2 _112_ (
    .A(_048_),
    .B(_059_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nand2b_2 _113_ (
    .A_N(\S0.clk_gen[2].clk_gen[1].clks.d[1] ),
    .B(\S0.stage_gen[1].mux_gen[2].S.PAR_IN1 ),
    .Y(_050_)
  );
  sky130_fd_sc_hd__nand2_2 _114_ (
    .A(PAR_IN[5]),
    .B(\S0.clk_gen[2].clk_gen[1].clks.d[1] ),
    .Y(_051_)
  );
  sky130_fd_sc_hd__nand3_2 _115_ (
    .A(_050_),
    .B(\S0.clk_gen[1].clk_gen[0].clks.clk90_o ),
    .C(_051_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__nand2_2 _116_ (
    .A(_001_),
    .B(\S0.stage_gen[1].mux_gen[3].S.PAR_IN1 ),
    .Y(_004_)
  );
  sky130_fd_sc_hd__nand2_2 _117_ (
    .A(\S0.clk_gen[2].clk_gen[1].clks.d[0] ),
    .B(PAR_IN[7]),
    .Y(_005_)
  );
  sky130_fd_sc_hd__nand3_2 _118_ (
    .A(_004_),
    .B(\S0.clk_gen[1].clk_gen[0].clks.d[0] ),
    .C(_005_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__nand3_2 _119_ (
    .A(_052_),
    .B(_006_),
    .C(\clkdiv0.d[1] ),
    .Y(_007_)
  );
  sky130_fd_sc_hd__nand2_4 _120_ (
    .A(_049_),
    .B(_007_),
    .Y(\S0.SERIAL_OUT )
  );
  sky130_fd_sc_hd__inv_2 _121_ (
    .A(\S1.stage_gen[1].mux_gen[1].S.PAR_IN1 ),
    .Y(_008_)
  );
  sky130_fd_sc_hd__nand2_4 _122_ (
    .A(_002_),
    .B(_008_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__inv_2 _123_ (
    .A(PAR_IN[11]),
    .Y(_010_)
  );
  sky130_fd_sc_hd__nand2_2 _124_ (
    .A(_010_),
    .B(\S1.clk_gen[2].clk_gen[0].clks.d[0] ),
    .Y(_011_)
  );
  sky130_fd_sc_hd__nand3_2 _125_ (
    .A(_009_),
    .B(_011_),
    .C(\S1.clk_gen[1].clk_gen[0].clks.d[1] ),
    .Y(_012_)
  );
  sky130_fd_sc_hd__inv_2 _126_ (
    .A(\S1.stage_gen[1].mux_gen[0].S.PAR_IN1 ),
    .Y(_013_)
  );
  sky130_fd_sc_hd__inv_2 _127_ (
    .A(\S1.clk_gen[2].clk_gen[0].clks.d[1] ),
    .Y(_014_)
  );
  sky130_fd_sc_hd__nand2_2 _128_ (
    .A(_013_),
    .B(_014_),
    .Y(_015_)
  );
  sky130_fd_sc_hd__inv_2 _129_ (
    .A(\S1.stage_gen[1].mux_gen[0].S.PAR_IN2 ),
    .Y(_016_)
  );
  sky130_fd_sc_hd__nand2_2 _130_ (
    .A(_016_),
    .B(\S1.clk_gen[2].clk_gen[0].clks.d[1] ),
    .Y(_017_)
  );
  sky130_fd_sc_hd__nand3_2 _131_ (
    .A(_015_),
    .B(_017_),
    .C(_063_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__nand2_2 _132_ (
    .A(_012_),
    .B(_018_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__nand2_2 _133_ (
    .A(_019_),
    .B(\S1.CLK ),
    .Y(_020_)
  );
  sky130_fd_sc_hd__nand2_2 _134_ (
    .A(_003_),
    .B(\S1.stage_gen[1].mux_gen[3].S.PAR_IN1 ),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nand2_2 _135_ (
    .A(\S1.clk_gen[2].clk_gen[1].clks.d[0] ),
    .B(PAR_IN[15]),
    .Y(_022_)
  );
  sky130_fd_sc_hd__nand3_2 _136_ (
    .A(_021_),
    .B(\S1.clk_gen[1].clk_gen[0].clks.d[0] ),
    .C(_022_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__inv_2 _137_ (
    .A(\S1.clk_gen[2].clk_gen[1].clks.d[1] ),
    .Y(_024_)
  );
  sky130_fd_sc_hd__nand2_2 _138_ (
    .A(_024_),
    .B(\S1.stage_gen[1].mux_gen[2].S.PAR_IN1 ),
    .Y(_025_)
  );
  sky130_fd_sc_hd__nand2_2 _139_ (
    .A(PAR_IN[13]),
    .B(\S1.clk_gen[2].clk_gen[1].clks.d[1] ),
    .Y(_026_)
  );
  sky130_fd_sc_hd__nand3_2 _140_ (
    .A(_025_),
    .B(\S1.clk_gen[1].clk_gen[0].clks.clk90_o ),
    .C(_026_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__nand3_2 _141_ (
    .A(_023_),
    .B(_027_),
    .C(\clkdiv0.d[0] ),
    .Y(_028_)
  );
  sky130_fd_sc_hd__nand2_4 _142_ (
    .A(_020_),
    .B(_028_),
    .Y(\S1.SERIAL_OUT )
  );
  sky130_fd_sc_hd__mux2_4 _143_ (
    .A0(\last_stage.PAR_IN2 ),
    .A1(\last_stage.PAR_IN1 ),
    .S(CLK),
    .X(_029_)
  );
  sky130_fd_sc_hd__buf_6 _144_ (
    .A(_029_),
    .X(SERIAL_OUT)
  );
  sky130_fd_sc_hd__buf_1 _145_ (
    .A(\S1.clk_gen[1].clk_gen[0].clks.d[1] ),
    .X(_030_)
  );
  sky130_fd_sc_hd__buf_2 _146_ (
    .A(_030_),
    .X(_064_)
  );
  sky130_fd_sc_hd__dlxtp_1 _147_ (
    .D(\S0.SERIAL_OUT ),
    .GATE(CLK),
    .Q(\last_stage_inputs[0] )
  );
  sky130_fd_sc_hd__dlxtn_1 _148_ (
    .D(\S1.SERIAL_OUT ),
    .GATE_N(CLK),
    .Q(\last_stage_inputs[1] )
  );
  sky130_fd_sc_hd__dlxtn_1 _149_ (
    .D(\last_stage_inputs[0] ),
    .GATE_N(CLK),
    .Q(\last_stage.PAR_IN1 )
  );
  sky130_fd_sc_hd__dlxtp_1 _150_ (
    .D(\last_stage_inputs[1] ),
    .GATE(CLK),
    .Q(\last_stage.PAR_IN2 )
  );
  sky130_fd_sc_hd__dlxtn_1 _151_ (
    .D(PAR_IN[1]),
    .GATE_N(CLK),
    .Q(\S0.stage_gen[1].mux_gen[0].S.PAR_IN2 )
  );
  sky130_fd_sc_hd__dlxtn_1 _152_ (
    .D(PAR_IN[3]),
    .GATE_N(CLK),
    .Q(\S0.stage_gen[1].mux_gen[1].S.PAR_IN2 )
  );
  sky130_fd_sc_hd__dlxtn_1 _153_ (
    .D(PAR_IN[4]),
    .GATE_N(CLK),
    .Q(\S0.stage_gen[1].mux_gen[2].S.PAR_IN1 )
  );
  sky130_fd_sc_hd__dlxtn_1 _154_ (
    .D(PAR_IN[6]),
    .GATE_N(CLK),
    .Q(\S0.stage_gen[1].mux_gen[3].S.PAR_IN1 )
  );
  sky130_fd_sc_hd__dlxtn_1 _155_ (
    .D(PAR_IN[9]),
    .GATE_N(CLK),
    .Q(\S1.stage_gen[1].mux_gen[0].S.PAR_IN2 )
  );
  sky130_fd_sc_hd__dlxtn_1 _156_ (
    .D(PAR_IN[10]),
    .GATE_N(CLK),
    .Q(\S1.stage_gen[1].mux_gen[1].S.PAR_IN1 )
  );
  sky130_fd_sc_hd__dlxtn_1 _157_ (
    .D(PAR_IN[12]),
    .GATE_N(CLK),
    .Q(\S1.stage_gen[1].mux_gen[2].S.PAR_IN1 )
  );
  sky130_fd_sc_hd__dlxtn_1 _158_ (
    .D(PAR_IN[14]),
    .GATE_N(CLK),
    .Q(\S1.stage_gen[1].mux_gen[3].S.PAR_IN1 )
  );
  sky130_fd_sc_hd__dfxtp_2 _159_ (
    .CLK(CLK),
    .D(PAR_IN[0]),
    .Q(\S0.stage_gen[1].mux_gen[0].S.PAR_IN1 )
  );
  sky130_fd_sc_hd__dfxtp_2 _160_ (
    .CLK(CLK),
    .D(PAR_IN[2]),
    .Q(\S0.stage_gen[1].mux_gen[1].S.PAR_IN1 )
  );
  sky130_fd_sc_hd__dfxtp_2 _161_ (
    .CLK(CLK),
    .D(PAR_IN[8]),
    .Q(\S1.stage_gen[1].mux_gen[0].S.PAR_IN1 )
  );
  sky130_fd_sc_hd__conb_1 _162_ (
    .LO(_067_)
  );
  sky130_fd_sc_hd__conb_1 _163_ (
    .LO(_068_)
  );
  sky130_fd_sc_hd__conb_1 _164_ (
    .LO(_069_)
  );
  sky130_fd_sc_hd__conb_1 _165_ (
    .LO(_070_)
  );
  sky130_fd_sc_hd__conb_1 _166_ (
    .LO(_071_)
  );
  sky130_fd_sc_hd__conb_1 _167_ (
    .LO(_072_)
  );
  sky130_fd_sc_hd__conb_1 _168_ (
    .LO(_073_)
  );
  sky130_fd_sc_hd__ebufn_2 _169_ (
    .A(\S1.CLK ),
    .TE_B(_053_),
    .Z(\clkdiv0.d[1] )
  );
  sky130_fd_sc_hd__ebufn_2 _170_ (
    .A(_067_),
    .TE_B(_054_),
    .Z(\clkdiv0.d[0] )
  );
  sky130_fd_sc_hd__ebufn_2 _171_ (
    .A(_068_),
    .TE_B(_055_),
    .Z(\S0.clk_gen[2].clk_gen[1].clks.d[0] )
  );
  sky130_fd_sc_hd__ebufn_2 _172_ (
    .A(_001_),
    .TE_B(_056_),
    .Z(\S0.clk_gen[2].clk_gen[1].clks.d[1] )
  );
  sky130_fd_sc_hd__ebufn_2 _173_ (
    .A(_069_),
    .TE_B(_057_),
    .Z(\S0.clk_gen[2].clk_gen[0].clks.d[0] )
  );
  sky130_fd_sc_hd__ebufn_2 _174_ (
    .A(_000_),
    .TE_B(_058_),
    .Z(\S0.clk_gen[2].clk_gen[0].clks.d[1] )
  );
  sky130_fd_sc_hd__ebufn_2 _175_ (
    .A(_070_),
    .TE_B(_059_),
    .Z(\S0.clk_gen[1].clk_gen[0].clks.d[0] )
  );
  sky130_fd_sc_hd__ebufn_2 _176_ (
    .A(\S0.clk_gen[1].clk_gen[0].clks.clk90_o ),
    .TE_B(_060_),
    .Z(\S0.clk_gen[1].clk_gen[0].clks.d[1] )
  );
  sky130_fd_sc_hd__ebufn_2 _177_ (
    .A(_071_),
    .TE_B(_061_),
    .Z(\S1.clk_gen[2].clk_gen[1].clks.d[0] )
  );
  sky130_fd_sc_hd__ebufn_2 _178_ (
    .A(_003_),
    .TE_B(_062_),
    .Z(\S1.clk_gen[2].clk_gen[1].clks.d[1] )
  );
  sky130_fd_sc_hd__ebufn_2 _179_ (
    .A(_072_),
    .TE_B(_063_),
    .Z(\S1.clk_gen[2].clk_gen[0].clks.d[0] )
  );
  sky130_fd_sc_hd__ebufn_2 _180_ (
    .A(_002_),
    .TE_B(_064_),
    .Z(\S1.clk_gen[2].clk_gen[0].clks.d[1] )
  );
  sky130_fd_sc_hd__ebufn_2 _181_ (
    .A(_073_),
    .TE_B(_065_),
    .Z(\S1.clk_gen[1].clk_gen[0].clks.d[0] )
  );
  sky130_fd_sc_hd__ebufn_2 _182_ (
    .A(\S1.clk_gen[1].clk_gen[0].clks.clk90_o ),
    .TE_B(_066_),
    .Z(\S1.clk_gen[1].clk_gen[0].clks.d[1] )
  );
endmodule
